use jni::objects::JString;

use crate::Result;
use crate::jni_utils::{get_env, JavaObject, JniValue};

#[derive(Debug, Clone)]
pub struct Block {
    pub inner: JavaObject,
}

impl Block {
    pub fn with_property(&self, key: &str, value: &str) -> Result<Block> {
        // Acquire the JNI environment
        let mut env = get_env()?;
        // Convert the Rust &str into Java strings
        let jkey: JString = env.new_string(key)?;
        let jvalue: JString = env.new_string(value)?;
        // Invoke the Java method with the correct JNI signature
        let result_obj = self.inner.call_object_method(
            "withProperty",
            "(Ljava/lang/String;Ljava/lang/String;)Lnet/minestom/server/instance/block/Block;",
            &[
                JniValue::String(jkey.into()),
                JniValue::String(jvalue.into()),
            ],
        )?;
        // Wrap the returned JavaObject into our Rust Block type
        Ok(Block { inner: result_obj })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockType {
    // Basic blocks
    Air,
    Stone,
    Granite,
    PolishedGranite,
    Diorite,
    PolishedDiorite,
    Andesite,
    PolishedAndesite,
    GrassBlock,
    Dirt,
    CoarseDirt,
    Podzol,
    Cobblestone,

    // Wood types and variants
    OakPlanks,
    SprucePlanks,
    BirchPlanks,
    JunglePlanks,
    AcaciaPlanks,
    CherryPlanks,
    DarkOakPlanks,
    PaleOakWood,
    PaleOakPlanks,
    MangrovePlanks,
    BambooPlanks,
    BambooMosaic,

    // Saplings
    OakSapling,
    SpruceSapling,
    BirchSapling,
    JungleSapling,
    AcaciaSapling,
    CherrySapling,
    DarkOakSapling,
    PaleOakSapling,
    MangrovePropagule,

    // Base blocks
    Bedrock,
    Water,
    Lava,
    Sand,
    SuspiciousSand,
    RedSand,
    Gravel,
    SuspiciousGravel,

    // Ores
    GoldOre,
    DeepslateGoldOre,
    IronOre,
    DeepslateIronOre,
    CoalOre,
    DeepslateCoalOre,
    NetherGoldOre,
    LapisOre,
    DeepslateLapisOre,
    DiamondOre,
    DeepslateDiamondOre,
    RedstoneOre,
    DeepslateRedstoneOre,
    EmeraldOre,
    DeepslateEmeraldOre,
    CopperOre,
    DeepslateCopperOre,

    // Logs
    OakLog,
    SpruceLog,
    BirchLog,
    JungleLog,
    AcaciaLog,
    CherryLog,
    DarkOakLog,
    PaleOakLog,
    MangroveLog,
    MangroveRoots,
    MuddyMangroveRoots,
    BambooBlock,

    // Stripped logs
    StrippedSpruceLog,
    StrippedBirchLog,
    StrippedJungleLog,
    StrippedAcaciaLog,
    StrippedCherryLog,
    StrippedDarkOakLog,
    StrippedPaleOakLog,
    StrippedOakLog,
    StrippedMangroveLog,
    StrippedBambooBlock,

    // Wood blocks
    OakWood,
    SpruceWood,
    BirchWood,
    JungleWood,
    AcaciaWood,
    CherryWood,
    DarkOakWood,
    MangroveWood,

    // Stripped wood
    StrippedOakWood,
    StrippedSpruceWood,
    StrippedBirchWood,
    StrippedJungleWood,
    StrippedAcaciaWood,
    StrippedCherryWood,
    StrippedDarkOakWood,
    StrippedPaleOakWood,
    StrippedMangroveWood,

    // Leaves
    OakLeaves,
    SpruceLeaves,
    BirchLeaves,
    JungleLeaves,
    AcaciaLeaves,
    CherryLeaves,
    DarkOakLeaves,
    PaleOakLeaves,
    MangroveLeaves,
    AzaleaLeaves,
    FloweringAzaleaLeaves,

    // Utility blocks
    Sponge,
    WetSponge,
    Glass,
    LapisBlock,
    Dispenser,

    // Sandstone variants
    Sandstone,
    ChiseledSandstone,
    CutSandstone,
    SmoothSandstone,
    RedSandstone,
    ChiseledRedSandstone,
    CutRedSandstone,
    SmoothRedSandstone,

    // Functional blocks
    NoteBlock,
    PoweredRail,
    DetectorRail,
    StickyPiston,
    Cobweb,
    TallGrass,
    Fern,
    DeadBush,
    Seagrass,
    TallSeagrass,
    Piston,
    PistonHead,

    // Wool colors
    WhiteWool,
    OrangeWool,
    MagentaWool,
    LightBlueWool,
    YellowWool,
    LimeWool,
    PinkWool,
    GrayWool,
    LightGrayWool,
    CyanWool,
    PurpleWool,
    BlueWool,
    BrownWool,
    GreenWool,
    RedWool,
    BlackWool,

    // Flowers
    Dandelion,
    Poppy,
    BlueOrchid,
    Allium,
    AzureBluet,
    RedTulip,
    OrangeTulip,
    WhiteTulip,
    PinkTulip,
    OxeyeDaisy,
    Cornflower,
    LilyOfTheValley,
    WitherRose,

    // Mushrooms
    BrownMushroom,
    RedMushroom,
    MushroomStem,
    BrownMushroomBlock,
    RedMushroomBlock,

    // Metal blocks
    GoldBlock,
    IronBlock,
    DiamondBlock,
    EmeraldBlock,
    CopperBlock,

    // Building blocks
    Bricks,
    Tnt,
    Bookshelf,
    MossyCobblestone,
    Obsidian,
    Torch,
    WallTorch,
    Fire,
    SoulFire,

    // Colored Concrete
    WhiteConcrete,
    OrangeConcrete,
    MagentaConcrete,
    LightBlueConcrete,
    YellowConcrete,
    LimeConcrete,
    PinkConcrete,
    GrayConcrete,
    LightGrayConcrete,
    CyanConcrete,
    PurpleConcrete,
    BlueConcrete,
    BrownConcrete,
    GreenConcrete,
    RedConcrete,
    BlackConcrete,

    // Colored Concrete Powder
    WhiteConcretePowder,
    OrangeConcretePowder,
    MagentaConcretePowder,
    LightBlueConcretePowder,
    YellowConcretePowder,
    LimeConcretePowder,
    PinkConcretePowder,
    GrayConcretePowder,
    LightGrayConcretePowder,
    CyanConcretePowder,
    PurpleConcretePowder,
    BlueConcretePowder,
    BrownConcretePowder,
    GreenConcretePowder,
    RedConcretePowder,
    BlackConcretePowder,

    // Colored Terracotta
    WhiteTerracotta,
    OrangeTerracotta,
    MagentaTerracotta,
    LightBlueTerracotta,
    YellowTerracotta,
    LimeTerracotta,
    PinkTerracotta,
    GrayTerracotta,
    LightGrayTerracotta,
    CyanTerracotta,
    PurpleTerracotta,
    BlueTerracotta,
    BrownTerracotta,
    GreenTerracotta,
    RedTerracotta,
    BlackTerracotta,
    Terracotta,

    // Colored Stained Glass
    WhiteStainedGlass,
    OrangeStainedGlass,
    MagentaStainedGlass,
    LightBlueStainedGlass,
    YellowStainedGlass,
    LimeStainedGlass,
    PinkStainedGlass,
    GrayStainedGlass,
    LightGrayStainedGlass,
    CyanStainedGlass,
    PurpleStainedGlass,
    BlueStainedGlass,
    BrownStainedGlass,
    GreenStainedGlass,
    RedStainedGlass,
    BlackStainedGlass,

    // Stairs
    OakStairs,
    SpruceStairs,
    BirchStairs,
    JungleStairs,
    AcaciaStairs,
    DarkOakStairs,
    CrimsonStairs,
    WarpedStairs,
    StoneStairs,
    CobblestoneStairs,
    MossyCobblestoneStairs,
    StoneBrickStairs,
    MossyStoneBrickStairs,
    BrickStairs,
    SandstoneStairs,
    RedSandstoneStairs,
    NetherBrickStairs,
    QuartzStairs,
    PurpurStairs,

    // Slabs
    OakSlab,
    SpruceSlab,
    BirchSlab,
    JungleSlab,
    AcaciaSlab,
    DarkOakSlab,
    CrimsonSlab,
    WarpedSlab,
    StoneSlab,
    CobblestoneSlab,
    MossyCobblestoneSlab,
    StoneBrickSlab,
    MossyStoneBrickSlab,
    BrickSlab,
    SandstoneSlab,
    RedSandstoneSlab,
    NetherBrickSlab,
    QuartzSlab,
    PurpurSlab,

    // Walls
    CobblestoneWall,
    MossyCobblestoneWall,
    BrickWall,
    StoneBrickWall,
    MossyStoneBrickWall,
    SandstoneWall,
    RedSandstoneWall,
    NetherBrickWall,
    EndStoneBrickWall,
    PrismarineWall,

    // Doors
    OakDoor,
    SpruceDoor,
    BirchDoor,
    JungleDoor,
    AcaciaDoor,
    DarkOakDoor,
    CrimsonDoor,
    WarpedDoor,
    IronDoor,

    // Trapdoors
    OakTrapdoor,
    SpruceTrapdoor,
    BirchTrapdoor,
    JungleTrapdoor,
    AcaciaTrapdoor,
    DarkOakTrapdoor,
    CrimsonTrapdoor,
    WarpedTrapdoor,
    IronTrapdoor,

    // Pressure Plates
    OakPressurePlate,
    SprucePressurePlate,
    BirchPressurePlate,
    JunglePressurePlate,
    AcaciaPressurePlate,
    DarkOakPressurePlate,
    CrimsonPressurePlate,
    WarpedPressurePlate,
    StonePressurePlate,
    LightWeightedPressurePlate,
    HeavyWeightedPressurePlate,

    // Buttons
    OakButton,
    SpruceButton,
    BirchButton,
    JungleButton,
    AcaciaButton,
    DarkOakButton,
    CrimsonButton,
    WarpedButton,
    StoneButton,
    PolishedBlackstoneButton,

    // Redstone Components
    RedstoneWire,
    RedstoneTorch,
    RedstoneWallTorch,
    RepeatingRepeater,
    ComparatorRepeater,
    Lever,
    DaylightDetector,
    Hopper,
    Dropper,
    Observer,
    Target,

    // Decorative
    Ladder,
    Scaffolding,
    IronBars,
    Chain,
    GlassPane,
    Vine,
    Lily,
    EnderChest,
    Anvil,
    Grindstone,
    Lectern,
    Campfire,
    SoulCampfire,
    Lantern,
    SoulLantern,
    Bell,
    Barrel,
    Composter,
    Loom,
    Smoker,
    BlastFurnace,
    Cartography,
    FletchingTable,
    SmithingTable,
    Cauldron,
    Jukebox,
    Beacon,
    ConduitBlock,

    // Nether blocks
    NetherBricks,
    ChiseledNetherBricks,
    CrackedNetherBricks,
    NetherWart,
    NetherWartBlock,
    Netherrack,
    SoulSand,
    SoulSoil,
    Basalt,
    PolishedBasalt,
    Blackstone,
    PolishedBlackstone,
    ChiseledPolishedBlackstone,
    PolishedBlackstoneBricks,
    CrackedPolishedBlackstoneBricks,
    GildedBlackstone,
    QuartzBlock,
    ChiseledQuartzBlock,
    QuartzBricks,
    QuartzPillar,
    SmoothQuartz,
    Glowstone,
    CryingObsidian,
    RespawnAnchor,
    AncientDebris,
    NetheriteBlock,

    // End blocks
    EndStone,
    EndStoneBricks,
    DragonEgg,
    Chorus,
    ChorusFlower,
    ChorusPlant,
    PurpurBlock,
    PurpurPillar,
    EndRod,

    // Ocean blocks
    Prismarine,
    PrismarineBricks,
    DarkPrismarine,
    SeaLantern,
    Kelp,
    KelpPlant,
    SeaPickle,
    TurtleEgg,
    DriedKelpBlock,

    // Snow and ice
    Snow,
    SnowBlock,
    Ice,
    PackedIce,
    BlueIce,
    FrostedIce,

    // Miscellaneous
    SlimeBlock,
    HoneyBlock,
    HoneycombBlock,
    Hay,
    BoneBlock,
    DriedKelp,
    Bamboo,
    BambooSapling,
    PottedBamboo,
    FlowerPot,
    Cactus,
    Cake,
    Cookie,
    MelonBlock,
    PumpkinBlock,
    CarvedPumpkin,
    JackOLantern,
    Beetroots,
    Carrots,
    Potatoes,
    Wheat,
    FarmLand,
    CommandBlock,
    ChainCommandBlock,
    RepeatingCommandBlock,
    StructureBlock,
    JigsawBlock,
    Barrier,
    Light,
    VoidAir,
    CaveAir,
    BubbleColumn,

    // Shulker boxes
    ShulkerBox,
    WhiteShulkerBox,
    OrangeShulkerBox,
    MagentaShulkerBox,
    LightBlueShulkerBox,
    YellowShulkerBox,
    LimeShulkerBox,
    PinkShulkerBox,
    GrayShulkerBox,
    LightGrayShulkerBox,
    CyanShulkerBox,
    PurpleShulkerBox,
    BlueShulkerBox,
    BrownShulkerBox,
    GreenShulkerBox,
    RedShulkerBox,
    BlackShulkerBox,
}

impl BlockType {
    pub fn to_block(&self) -> Result<Block> {
        let mut env = get_env()?;

        // Get the Block class
        let block_class = env.find_class("net/minestom/server/instance/block/Block")?;

        // Get the static block field
        let field_name = self.to_field_name();
        let block = env
            .get_static_field(
                block_class,
                field_name,
                "Lnet/minestom/server/instance/block/Block;",
            )?
            .l()?;
        let obj = JavaObject::from_env(&mut env, block)?;

        Ok(Block {
            inner: obj,
        })
    }

    fn to_field_name(&self) -> &'static str {
        match self {
            // Basic blocks
            BlockType::Air => "AIR",
            BlockType::Stone => "STONE",
            BlockType::Granite => "GRANITE",
            BlockType::PolishedGranite => "POLISHED_GRANITE",
            BlockType::Diorite => "DIORITE",
            BlockType::PolishedDiorite => "POLISHED_DIORITE",
            BlockType::Andesite => "ANDESITE",
            BlockType::PolishedAndesite => "POLISHED_ANDESITE",
            BlockType::GrassBlock => "GRASS_BLOCK",
            BlockType::Dirt => "DIRT",
            BlockType::CoarseDirt => "COARSE_DIRT",
            BlockType::Podzol => "PODZOL",
            BlockType::Cobblestone => "COBBLESTONE",

            // Ores
            BlockType::GoldOre => "GOLD_ORE",
            BlockType::DeepslateGoldOre => "DEEPSLATE_GOLD_ORE",
            BlockType::IronOre => "IRON_ORE",
            BlockType::DeepslateIronOre => "DEEPSLATE_IRON_ORE",
            BlockType::CoalOre => "COAL_ORE",
            BlockType::DeepslateCoalOre => "DEEPSLATE_COAL_ORE",
            BlockType::NetherGoldOre => "NETHER_GOLD_ORE",
            BlockType::DiamondOre => "DIAMOND_ORE",
            BlockType::DeepslateDiamondOre => "DEEPSLATE_DIAMOND_ORE",
            BlockType::RedstoneOre => "REDSTONE_ORE",
            BlockType::DeepslateRedstoneOre => "DEEPSLATE_REDSTONE_ORE",
            BlockType::EmeraldOre => "EMERALD_ORE",
            BlockType::DeepslateEmeraldOre => "DEEPSLATE_EMERALD_ORE",
            BlockType::CopperOre => "COPPER_ORE",
            BlockType::DeepslateCopperOre => "DEEPSLATE_COPPER_ORE",
            BlockType::LapisOre => "LAPIS_ORE",
            BlockType::DeepslateLapisOre => "DEEPSLATE_LAPIS_ORE",

            // Wood types and variants
            BlockType::OakPlanks => "OAK_PLANKS",
            BlockType::SprucePlanks => "SPRUCE_PLANKS",
            BlockType::BirchPlanks => "BIRCH_PLANKS",
            BlockType::JunglePlanks => "JUNGLE_PLANKS",
            BlockType::AcaciaPlanks => "ACACIA_PLANKS",
            BlockType::CherryPlanks => "CHERRY_PLANKS",
            BlockType::DarkOakPlanks => "DARK_OAK_PLANKS",
            BlockType::PaleOakWood => "PALE_OAK_WOOD",
            BlockType::PaleOakPlanks => "PALE_OAK_PLANKS",
            BlockType::MangrovePlanks => "MANGROVE_PLANKS",
            BlockType::BambooPlanks => "BAMBOO_PLANKS",
            BlockType::BambooMosaic => "BAMBOO_MOSAIC",

            // Saplings
            BlockType::OakSapling => "OAK_SAPLING",
            BlockType::SpruceSapling => "SPRUCE_SAPLING",
            BlockType::BirchSapling => "BIRCH_SAPLING",
            BlockType::JungleSapling => "JUNGLE_SAPLING",
            BlockType::AcaciaSapling => "ACACIA_SAPLING",
            BlockType::CherrySapling => "CHERRY_SAPLING",
            BlockType::DarkOakSapling => "DARK_OAK_SAPLING",
            BlockType::PaleOakSapling => "PALE_OAK_SAPLING",
            BlockType::MangrovePropagule => "MANGROVE_PROPAGULE",

            // Base blocks
            BlockType::Bedrock => "BEDROCK",
            BlockType::Water => "WATER",
            BlockType::Lava => "LAVA",
            BlockType::Sand => "SAND",
            BlockType::SuspiciousSand => "SUSPICIOUS_SAND",
            BlockType::RedSand => "RED_SAND",
            BlockType::Gravel => "GRAVEL",
            BlockType::SuspiciousGravel => "SUSPICIOUS_GRAVEL",

            // Logs
            BlockType::OakLog => "OAK_LOG",
            BlockType::SpruceLog => "SPRUCE_LOG",
            BlockType::BirchLog => "BIRCH_LOG",
            BlockType::JungleLog => "JUNGLE_LOG",
            BlockType::AcaciaLog => "ACACIA_LOG",
            BlockType::CherryLog => "CHERRY_LOG",
            BlockType::DarkOakLog => "DARK_OAK_LOG",
            BlockType::PaleOakLog => "PALE_OAK_LOG",
            BlockType::MangroveLog => "MANGROVE_LOG",
            BlockType::MangroveRoots => "MANGROVE_ROOTS",
            BlockType::MuddyMangroveRoots => "MUDDY_MANGROVE_ROOTS",
            BlockType::BambooBlock => "BAMBOO_BLOCK",

            // Stripped logs
            BlockType::StrippedSpruceLog => "STRIPPED_SPRUCE_LOG",
            BlockType::StrippedBirchLog => "STRIPPED_BIRCH_LOG",
            BlockType::StrippedJungleLog => "STRIPPED_JUNGLE_LOG",
            BlockType::StrippedAcaciaLog => "STRIPPED_ACACIA_LOG",
            BlockType::StrippedCherryLog => "STRIPPED_CHERRY_LOG",
            BlockType::StrippedDarkOakLog => "STRIPPED_DARK_OAK_LOG",
            BlockType::StrippedPaleOakLog => "STRIPPED_PALE_OAK_LOG",
            BlockType::StrippedOakLog => "STRIPPED_OAK_LOG",
            BlockType::StrippedMangroveLog => "STRIPPED_MANGROVE_LOG",
            BlockType::StrippedBambooBlock => "STRIPPED_BAMBOO_BLOCK",

            // Wood blocks
            BlockType::OakWood => "OAK_WOOD",
            BlockType::SpruceWood => "SPRUCE_WOOD",
            BlockType::BirchWood => "BIRCH_WOOD",
            BlockType::JungleWood => "JUNGLE_WOOD",
            BlockType::AcaciaWood => "ACACIA_WOOD",
            BlockType::CherryWood => "CHERRY_WOOD",
            BlockType::DarkOakWood => "DARK_OAK_WOOD",
            BlockType::MangroveWood => "MANGROVE_WOOD",

            // Stripped wood
            BlockType::StrippedOakWood => "STRIPPED_OAK_WOOD",
            BlockType::StrippedSpruceWood => "STRIPPED_SPRUCE_WOOD",
            BlockType::StrippedBirchWood => "STRIPPED_BIRCH_WOOD",
            BlockType::StrippedJungleWood => "STRIPPED_JUNGLE_WOOD",
            BlockType::StrippedAcaciaWood => "STRIPPED_ACACIA_WOOD",
            BlockType::StrippedCherryWood => "STRIPPED_CHERRY_WOOD",
            BlockType::StrippedDarkOakWood => "STRIPPED_DARK_OAK_WOOD",
            BlockType::StrippedPaleOakWood => "STRIPPED_PALE_OAK_WOOD",
            BlockType::StrippedMangroveWood => "STRIPPED_MANGROVE_WOOD",

            // Leaves
            BlockType::OakLeaves => "OAK_LEAVES",
            BlockType::SpruceLeaves => "SPRUCE_LEAVES",
            BlockType::BirchLeaves => "BIRCH_LEAVES",
            BlockType::JungleLeaves => "JUNGLE_LEAVES",
            BlockType::AcaciaLeaves => "ACACIA_LEAVES",
            BlockType::CherryLeaves => "CHERRY_LEAVES",
            BlockType::DarkOakLeaves => "DARK_OAK_LEAVES",
            BlockType::PaleOakLeaves => "PALE_OAK_LEAVES",
            BlockType::MangroveLeaves => "MANGROVE_LEAVES",
            BlockType::AzaleaLeaves => "AZALEA_LEAVES",
            BlockType::FloweringAzaleaLeaves => "FLOWERING_AZALEA_LEAVES",

            // Utility blocks
            BlockType::Sponge => "SPONGE",
            BlockType::WetSponge => "WET_SPONGE",
            BlockType::Glass => "GLASS",
            BlockType::LapisBlock => "LAPIS_BLOCK",
            BlockType::Dispenser => "DISPENSER",

            // Sandstone variants
            BlockType::Sandstone => "SANDSTONE",
            BlockType::ChiseledSandstone => "CHISELED_SANDSTONE",
            BlockType::CutSandstone => "CUT_SANDSTONE",
            BlockType::SmoothSandstone => "SMOOTH_SANDSTONE",
            BlockType::RedSandstone => "RED_SANDSTONE",
            BlockType::ChiseledRedSandstone => "CHISELED_RED_SANDSTONE",
            BlockType::CutRedSandstone => "CUT_RED_SANDSTONE",
            BlockType::SmoothRedSandstone => "SMOOTH_RED_SANDSTONE",

            // Functional blocks
            BlockType::NoteBlock => "NOTE_BLOCK",
            BlockType::PoweredRail => "POWERED_RAIL",
            BlockType::DetectorRail => "DETECTOR_RAIL",
            BlockType::StickyPiston => "STICKY_PISTON",
            BlockType::Cobweb => "COBWEB",
            BlockType::TallGrass => "TALL_GRASS",
            BlockType::Fern => "FERN",
            BlockType::DeadBush => "DEAD_BUSH",
            BlockType::Seagrass => "SEAGRASS",
            BlockType::TallSeagrass => "TALL_SEAGRASS",
            BlockType::Piston => "PISTON",
            BlockType::PistonHead => "PISTON_HEAD",

            // Wool colors
            BlockType::WhiteWool => "WHITE_WOOL",
            BlockType::OrangeWool => "ORANGE_WOOL",
            BlockType::MagentaWool => "MAGENTA_WOOL",
            BlockType::LightBlueWool => "LIGHT_BLUE_WOOL",
            BlockType::YellowWool => "YELLOW_WOOL",
            BlockType::LimeWool => "LIME_WOOL",
            BlockType::PinkWool => "PINK_WOOL",
            BlockType::GrayWool => "GRAY_WOOL",
            BlockType::LightGrayWool => "LIGHT_GRAY_WOOL",
            BlockType::CyanWool => "CYAN_WOOL",
            BlockType::PurpleWool => "PURPLE_WOOL",
            BlockType::BlueWool => "BLUE_WOOL",
            BlockType::BrownWool => "BROWN_WOOL",
            BlockType::GreenWool => "GREEN_WOOL",
            BlockType::RedWool => "RED_WOOL",
            BlockType::BlackWool => "BLACK_WOOL",

            // Flowers
            BlockType::Dandelion => "DANDELION",
            BlockType::Poppy => "POPPY",
            BlockType::BlueOrchid => "BLUE_ORCHID",
            BlockType::Allium => "ALLIUM",
            BlockType::AzureBluet => "AZURE_BLUET",
            BlockType::RedTulip => "RED_TULIP",
            BlockType::OrangeTulip => "ORANGE_TULIP",
            BlockType::WhiteTulip => "WHITE_TULIP",
            BlockType::PinkTulip => "PINK_TULIP",
            BlockType::OxeyeDaisy => "OXEYE_DAISY",
            BlockType::Cornflower => "CORNFLOWER",
            BlockType::LilyOfTheValley => "LILY_OF_THE_VALLEY",
            BlockType::WitherRose => "WITHER_ROSE",

            // Mushrooms
            BlockType::BrownMushroom => "BROWN_MUSHROOM",
            BlockType::RedMushroom => "RED_MUSHROOM",
            BlockType::MushroomStem => "MUSHROOM_STEM",
            BlockType::BrownMushroomBlock => "BROWN_MUSHROOM_BLOCK",
            BlockType::RedMushroomBlock => "RED_MUSHROOM_BLOCK",

            // Metal blocks
            BlockType::GoldBlock => "GOLD_BLOCK",
            BlockType::IronBlock => "IRON_BLOCK",
            BlockType::DiamondBlock => "DIAMOND_BLOCK",
            BlockType::EmeraldBlock => "EMERALD_BLOCK",
            BlockType::CopperBlock => "COPPER_BLOCK",

            // Building blocks
            BlockType::Bricks => "BRICKS",
            BlockType::Tnt => "TNT",
            BlockType::Bookshelf => "BOOKSHELF",
            BlockType::MossyCobblestone => "MOSSY_COBBLESTONE",
            BlockType::Obsidian => "OBSIDIAN",
            BlockType::Torch => "TORCH",
            BlockType::WallTorch => "WALL_TORCH",
            BlockType::Fire => "FIRE",
            BlockType::SoulFire => "SOUL_FIRE",

            // Colored Concrete
            BlockType::WhiteConcrete => "WHITE_CONCRETE",
            BlockType::OrangeConcrete => "ORANGE_CONCRETE",
            BlockType::MagentaConcrete => "MAGENTA_CONCRETE",
            BlockType::LightBlueConcrete => "LIGHT_BLUE_CONCRETE",
            BlockType::YellowConcrete => "YELLOW_CONCRETE",
            BlockType::LimeConcrete => "LIME_CONCRETE",
            BlockType::PinkConcrete => "PINK_CONCRETE",
            BlockType::GrayConcrete => "GRAY_CONCRETE",
            BlockType::LightGrayConcrete => "LIGHT_GRAY_CONCRETE",
            BlockType::CyanConcrete => "CYAN_CONCRETE",
            BlockType::PurpleConcrete => "PURPLE_CONCRETE",
            BlockType::BlueConcrete => "BLUE_CONCRETE",
            BlockType::BrownConcrete => "BROWN_CONCRETE",
            BlockType::GreenConcrete => "GREEN_CONCRETE",
            BlockType::RedConcrete => "RED_CONCRETE",
            BlockType::BlackConcrete => "BLACK_CONCRETE",

            // Colored Concrete Powder
            BlockType::WhiteConcretePowder => "WHITE_CONCRETE_POWDER",
            BlockType::OrangeConcretePowder => "ORANGE_CONCRETE_POWDER",
            BlockType::MagentaConcretePowder => "MAGENTA_CONCRETE_POWDER",
            BlockType::LightBlueConcretePowder => "LIGHT_BLUE_CONCRETE_POWDER",
            BlockType::YellowConcretePowder => "YELLOW_CONCRETE_POWDER",
            BlockType::LimeConcretePowder => "LIME_CONCRETE_POWDER",
            BlockType::PinkConcretePowder => "PINK_CONCRETE_POWDER",
            BlockType::GrayConcretePowder => "GRAY_CONCRETE_POWDER",
            BlockType::LightGrayConcretePowder => "LIGHT_GRAY_CONCRETE_POWDER",
            BlockType::CyanConcretePowder => "CYAN_CONCRETE_POWDER",
            BlockType::PurpleConcretePowder => "PURPLE_CONCRETE_POWDER",
            BlockType::BlueConcretePowder => "BLUE_CONCRETE_POWDER",
            BlockType::BrownConcretePowder => "BROWN_CONCRETE_POWDER",
            BlockType::GreenConcretePowder => "GREEN_CONCRETE_POWDER",
            BlockType::RedConcretePowder => "RED_CONCRETE_POWDER",
            BlockType::BlackConcretePowder => "BLACK_CONCRETE_POWDER",

            // Colored Terracotta
            BlockType::WhiteTerracotta => "WHITE_TERRACOTTA",
            BlockType::OrangeTerracotta => "ORANGE_TERRACOTTA",
            BlockType::MagentaTerracotta => "MAGENTA_TERRACOTTA",
            BlockType::LightBlueTerracotta => "LIGHT_BLUE_TERRACOTTA",
            BlockType::YellowTerracotta => "YELLOW_TERRACOTTA",
            BlockType::LimeTerracotta => "LIME_TERRACOTTA",
            BlockType::PinkTerracotta => "PINK_TERRACOTTA",
            BlockType::GrayTerracotta => "GRAY_TERRACOTTA",
            BlockType::LightGrayTerracotta => "LIGHT_GRAY_TERRACOTTA",
            BlockType::CyanTerracotta => "CYAN_TERRACOTTA",
            BlockType::PurpleTerracotta => "PURPLE_TERRACOTTA",
            BlockType::BlueTerracotta => "BLUE_TERRACOTTA",
            BlockType::BrownTerracotta => "BROWN_TERRACOTTA",
            BlockType::GreenTerracotta => "GREEN_TERRACOTTA",
            BlockType::RedTerracotta => "RED_TERRACOTTA",
            BlockType::BlackTerracotta => "BLACK_TERRACOTTA",
            BlockType::Terracotta => "TERRACOTTA",

            // Colored Stained Glass
            BlockType::WhiteStainedGlass => "WHITE_STAINED_GLASS",
            BlockType::OrangeStainedGlass => "ORANGE_STAINED_GLASS",
            BlockType::MagentaStainedGlass => "MAGENTA_STAINED_GLASS",
            BlockType::LightBlueStainedGlass => "LIGHT_BLUE_STAINED_GLASS",
            BlockType::YellowStainedGlass => "YELLOW_STAINED_GLASS",
            BlockType::LimeStainedGlass => "LIME_STAINED_GLASS",
            BlockType::PinkStainedGlass => "PINK_STAINED_GLASS",
            BlockType::GrayStainedGlass => "GRAY_STAINED_GLASS",
            BlockType::LightGrayStainedGlass => "LIGHT_GRAY_STAINED_GLASS",
            BlockType::CyanStainedGlass => "CYAN_STAINED_GLASS",
            BlockType::PurpleStainedGlass => "PURPLE_STAINED_GLASS",
            BlockType::BlueStainedGlass => "BLUE_STAINED_GLASS",
            BlockType::BrownStainedGlass => "BROWN_STAINED_GLASS",
            BlockType::GreenStainedGlass => "GREEN_STAINED_GLASS",
            BlockType::RedStainedGlass => "RED_STAINED_GLASS",
            BlockType::BlackStainedGlass => "BLACK_STAINED_GLASS",

            // Stairs
            BlockType::OakStairs => "OAK_STAIRS",
            BlockType::SpruceStairs => "SPRUCE_STAIRS",
            BlockType::BirchStairs => "BIRCH_STAIRS",
            BlockType::JungleStairs => "JUNGLE_STAIRS",
            BlockType::AcaciaStairs => "ACACIA_STAIRS",
            BlockType::DarkOakStairs => "DARK_OAK_STAIRS",
            BlockType::CrimsonStairs => "CRIMSON_STAIRS",
            BlockType::WarpedStairs => "WARPED_STAIRS",
            BlockType::StoneStairs => "STONE_STAIRS",
            BlockType::CobblestoneStairs => "COBBLESTONE_STAIRS",
            BlockType::MossyCobblestoneStairs => "MOSSY_COBBLESTONE_STAIRS",
            BlockType::StoneBrickStairs => "STONE_BRICK_STAIRS",
            BlockType::MossyStoneBrickStairs => "MOSSY_STONE_BRICK_STAIRS",
            BlockType::BrickStairs => "BRICK_STAIRS",
            BlockType::SandstoneStairs => "SANDSTONE_STAIRS",
            BlockType::RedSandstoneStairs => "RED_SANDSTONE_STAIRS",
            BlockType::NetherBrickStairs => "NETHER_BRICK_STAIRS",
            BlockType::QuartzStairs => "QUARTZ_STAIRS",
            BlockType::PurpurStairs => "PURPUR_STAIRS",
            BlockType::OakSlab => "OAK_SLAB",
            BlockType::SpruceSlab => "SPRUCE_SLAB",
            BlockType::BirchSlab => "BIRCH_SLAB",
            BlockType::JungleSlab => "JUNGLE_SLAB",
            BlockType::AcaciaSlab => "ACACIA_SLAB",
            BlockType::DarkOakSlab => "DARK_OAK_SLAB",
            BlockType::CrimsonSlab => "CRIMSON_SLAB",
            BlockType::WarpedSlab => "WARPED_SLAB",
            BlockType::StoneSlab => "STONE_SLAB",
            BlockType::CobblestoneSlab => "COBBLESTONE_SLAB",
            BlockType::MossyCobblestoneSlab => "MOSSY_COBBLESTONE_SLAB",
            BlockType::StoneBrickSlab => "STONE_BRICK_SLAB",
            BlockType::MossyStoneBrickSlab => "MOSSY_STONE_BRICK_SLAB",
            BlockType::BrickSlab => "BRICK_SLAB",
            BlockType::SandstoneSlab => "SANDSTONE_SLAB",
            BlockType::RedSandstoneSlab => "RED_SANDSTONE_SLAB",
            BlockType::NetherBrickSlab => "NETHER_BRICK_SLAB",
            BlockType::QuartzSlab => "QUARTZ_SLAB",
            BlockType::PurpurSlab => "PURPUR_SLAB",
            BlockType::CobblestoneWall => "COBBLESTONE_WALL",
            BlockType::MossyCobblestoneWall => "MOSSY_COBBLESTONE_WALL",
            BlockType::BrickWall => "BRICK_WALL",
            BlockType::StoneBrickWall => "STONE_BRICK_WALL",
            BlockType::MossyStoneBrickWall => "MOSSY_STONE_BRICK_WALL",
            BlockType::SandstoneWall => "SANDSTONE_WALL",
            BlockType::RedSandstoneWall => "RED_SANDSTONE_WALL",
            BlockType::NetherBrickWall => "NETHER_BRICK_WALL",
            BlockType::EndStoneBrickWall => "END_STONE_BRICK_WALL",
            BlockType::PrismarineWall => "PRISMARINE_WALL",
            BlockType::OakDoor => "OAK_DOOR",
            BlockType::SpruceDoor => "SPRUCE_DOOR",
            BlockType::BirchDoor => "BIRCH_DOOR",
            BlockType::JungleDoor => "JUNGLE_DOOR",
            BlockType::AcaciaDoor => "ACACIA_DOOR",
            BlockType::DarkOakDoor => "DARK_OAK_DOOR",
            BlockType::CrimsonDoor => "CRIMSON_DOOR",
            BlockType::WarpedDoor => "WARPED_DOOR",
            BlockType::IronDoor => "IRON_DOOR",
            BlockType::OakTrapdoor => "OAK_TRAPDOOR",
            BlockType::SpruceTrapdoor => "SPRUCE_TRAPDOOR",
            BlockType::BirchTrapdoor => "BIRCH_TRAPDOOR",
            BlockType::JungleTrapdoor => "JUNGLE_TRAPDOOR",
            BlockType::AcaciaTrapdoor => "ACACIA_TRAPDOOR",
            BlockType::DarkOakTrapdoor => "DARK_OAK_TRAPDOOR",
            BlockType::CrimsonTrapdoor => "CRIMSON_TRAPDOOR",
            BlockType::WarpedTrapdoor => "WARPED_TRAPDOOR",
            BlockType::IronTrapdoor => "IRON_TRAPDOOR",
            BlockType::OakPressurePlate => "OAK_PRESSURE_PLATE",
            BlockType::SprucePressurePlate => "SPRUCE_PRESSURE_PLATE",
            BlockType::BirchPressurePlate => "BIRCH_PRESSURE_PLATE",
            BlockType::JunglePressurePlate => "JUNGLE_PRESSURE_PLATE",
            BlockType::AcaciaPressurePlate => "ACACIA_PRESSURE_PLATE",
            BlockType::DarkOakPressurePlate => "DARK_OAK_PRESSURE_PLATE",
            BlockType::CrimsonPressurePlate => "CRIMSON_PRESSURE_PLATE",
            BlockType::WarpedPressurePlate => "WARPED_PRESSURE_PLATE",
            BlockType::StonePressurePlate => "STONE_PRESSURE_PLATE",
            BlockType::LightWeightedPressurePlate => "LIGHT_WEIGHTED_PRESSURE_PLATE",
            BlockType::HeavyWeightedPressurePlate => "HEAVY_WEIGHTED_PRESSURE_PLATE",
            BlockType::OakButton => "OAK_BUTTON",
            BlockType::SpruceButton => "SPRUCE_BUTTON",
            BlockType::BirchButton => "BIRCH_BUTTON",
            BlockType::JungleButton => "JUNGLE_BUTTON",
            BlockType::AcaciaButton => "ACACIA_BUTTON",
            BlockType::DarkOakButton => "DARK_OAK_BUTTON",
            BlockType::CrimsonButton => "CRIMSON_BUTTON",
            BlockType::WarpedButton => "WARPED_BUTTON",
            BlockType::StoneButton => "STONE_BUTTON",
            BlockType::PolishedBlackstoneButton => "POLISHED_BLACKSTONE_BUTTON",
            BlockType::RedstoneWire => "REDSTONE_WIRE",
            BlockType::RedstoneTorch => "REDSTONE_TORCH",
            BlockType::RedstoneWallTorch => "REDSTONE_WALL_TORCH",
            BlockType::RepeatingRepeater => "REPEATING_REPEATER",
            BlockType::ComparatorRepeater => "COMPARATOR_REPEATER",
            BlockType::Lever => "LEVER",
            BlockType::DaylightDetector => "DAYLIGHT_DETECTOR",
            BlockType::Hopper => "HOPPER",
            BlockType::Dropper => "DROPPER",
            BlockType::Observer => "OBSERVER",
            BlockType::Target => "TARGET",
            BlockType::Ladder => "LADDER",
            BlockType::Scaffolding => "SCAFFOLDING",
            BlockType::IronBars => "IRON_BARS",
            BlockType::Chain => "CHAIN",
            BlockType::GlassPane => "GLASS_PANE",
            BlockType::Vine => "VINE",
            BlockType::Lily => "LILY",
            BlockType::EnderChest => "ENDER_CHEST",
            BlockType::Anvil => "ANVIL",
            BlockType::Grindstone => "GRINDSTONE",
            BlockType::Lectern => "LECTERN",
            BlockType::Campfire => "CAMPFIRE",
            BlockType::SoulCampfire => "SOUL_CAMPFIRE",
            BlockType::Lantern => "LANTERN",
            BlockType::SoulLantern => "SOUL_LANTERN",
            BlockType::Bell => "BELL",
            BlockType::Barrel => "BARREL",
            BlockType::Composter => "COMPOSTER",
            BlockType::Loom => "LOOM",
            BlockType::Smoker => "SMOKER",
            BlockType::BlastFurnace => "BLAST_FURNACE",
            BlockType::Cartography => "CARTOGRAPHY_TABLE",
            BlockType::FletchingTable => "FLETCHING_TABLE",
            BlockType::SmithingTable => "SMITHING_TABLE",
            BlockType::Cauldron => "CAULDRON",
            BlockType::Jukebox => "JUKEBOX",
            BlockType::Beacon => "BEACON",
            BlockType::ConduitBlock => "CONDUIT",

            // Nether blocks
            BlockType::NetherBricks => "NETHER_BRICKS",
            BlockType::ChiseledNetherBricks => "CHISELED_NETHER_BRICKS",
            BlockType::CrackedNetherBricks => "CRACKED_NETHER_BRICKS",
            BlockType::NetherWart => "NETHER_WART",
            BlockType::NetherWartBlock => "NETHER_WART_BLOCK",
            BlockType::Netherrack => "NETHERRACK",
            BlockType::SoulSand => "SOUL_SAND",
            BlockType::SoulSoil => "SOUL_SOIL",
            BlockType::Basalt => "BASALT",
            BlockType::PolishedBasalt => "POLISHED_BASALT",
            BlockType::Blackstone => "BLACKSTONE",
            BlockType::PolishedBlackstone => "POLISHED_BLACKSTONE",
            BlockType::ChiseledPolishedBlackstone => "CHISELED_POLISHED_BLACKSTONE",
            BlockType::PolishedBlackstoneBricks => "POLISHED_BLACKSTONE_BRICKS",
            BlockType::CrackedPolishedBlackstoneBricks => "CRACKED_POLISHED_BLACKSTONE_BRICKS",
            BlockType::GildedBlackstone => "GILDED_BLACKSTONE",
            BlockType::QuartzBlock => "QUARTZ_BLOCK",
            BlockType::ChiseledQuartzBlock => "CHISELED_QUARTZ_BLOCK",
            BlockType::QuartzBricks => "QUARTZ_BRICKS",
            BlockType::QuartzPillar => "QUARTZ_PILLAR",
            BlockType::SmoothQuartz => "SMOOTH_QUARTZ",
            BlockType::Glowstone => "GLOWSTONE",
            BlockType::CryingObsidian => "CRYING_OBSIDIAN",
            BlockType::RespawnAnchor => "RESPAWN_ANCHOR",
            BlockType::AncientDebris => "ANCIENT_DEBRIS",
            BlockType::NetheriteBlock => "NETHERITE_BLOCK",

            // End blocks
            BlockType::EndStone => "END_STONE",
            BlockType::EndStoneBricks => "END_STONE_BRICKS",
            BlockType::DragonEgg => "DRAGON_EGG",
            BlockType::Chorus => "CHORUS",
            BlockType::ChorusFlower => "CHORUS_FLOWER",
            BlockType::ChorusPlant => "CHORUS_PLANT",
            BlockType::PurpurBlock => "PURPUR_BLOCK",
            BlockType::PurpurPillar => "PURPUR_PILLAR",
            BlockType::EndRod => "END_ROD",

            // Ocean blocks
            BlockType::Prismarine => "PRISMARINE",
            BlockType::PrismarineBricks => "PRISMARINE_BRICKS",
            BlockType::DarkPrismarine => "DARK_PRISMARINE",
            BlockType::SeaLantern => "SEA_LANTERN",
            BlockType::Kelp => "KELP",
            BlockType::KelpPlant => "KELP_PLANT",
            BlockType::SeaPickle => "SEA_PICKLE",
            BlockType::TurtleEgg => "TURTLE_EGG",
            BlockType::DriedKelpBlock => "DRIED_KELP_BLOCK",

            // Snow and ice
            BlockType::Snow => "SNOW",
            BlockType::SnowBlock => "SNOW_BLOCK",
            BlockType::Ice => "ICE",
            BlockType::PackedIce => "PACKED_ICE",
            BlockType::BlueIce => "BLUE_ICE",
            BlockType::FrostedIce => "FROSTED_ICE",

            // Miscellaneous
            BlockType::SlimeBlock => "SLIME_BLOCK",
            BlockType::HoneyBlock => "HONEY_BLOCK",
            BlockType::HoneycombBlock => "HONEYCOMB_BLOCK",
            BlockType::Hay => "HAY_BLOCK",
            BlockType::BoneBlock => "BONE_BLOCK",
            BlockType::DriedKelp => "DRIED_KELP",
            BlockType::Bamboo => "BAMBOO",
            BlockType::BambooSapling => "BAMBOO_SAPLING",
            BlockType::PottedBamboo => "POTTED_BAMBOO",
            BlockType::FlowerPot => "FLOWER_POT",
            BlockType::Cactus => "CACTUS",
            BlockType::Cake => "CAKE",
            BlockType::Cookie => "COOKIE",
            BlockType::MelonBlock => "MELON",
            BlockType::PumpkinBlock => "PUMPKIN",
            BlockType::CarvedPumpkin => "CARVED_PUMPKIN",
            BlockType::JackOLantern => "JACK_O_LANTERN",
            BlockType::Beetroots => "BEETROOTS",
            BlockType::Carrots => "CARROTS",
            BlockType::Potatoes => "POTATOES",
            BlockType::Wheat => "WHEAT",
            BlockType::FarmLand => "FARMLAND",
            BlockType::CommandBlock => "COMMAND_BLOCK",
            BlockType::ChainCommandBlock => "CHAIN_COMMAND_BLOCK",
            BlockType::RepeatingCommandBlock => "REPEATING_COMMAND_BLOCK",
            BlockType::StructureBlock => "STRUCTURE_BLOCK",
            BlockType::JigsawBlock => "JIGSAW",
            BlockType::Barrier => "BARRIER",
            BlockType::Light => "LIGHT",
            BlockType::VoidAir => "VOID_AIR",
            BlockType::CaveAir => "CAVE_AIR",
            BlockType::BubbleColumn => "BUBBLE_COLUMN",

            // Shulker boxes
            BlockType::ShulkerBox => "SHULKER_BOX",
            BlockType::WhiteShulkerBox => "WHITE_SHULKER_BOX",
            BlockType::OrangeShulkerBox => "ORANGE_SHULKER_BOX",
            BlockType::MagentaShulkerBox => "MAGENTA_SHULKER_BOX",
            BlockType::LightBlueShulkerBox => "LIGHT_BLUE_SHULKER_BOX",
            BlockType::YellowShulkerBox => "YELLOW_SHULKER_BOX",
            BlockType::LimeShulkerBox => "LIME_SHULKER_BOX",
            BlockType::PinkShulkerBox => "PINK_SHULKER_BOX",
            BlockType::GrayShulkerBox => "GRAY_SHULKER_BOX",
            BlockType::LightGrayShulkerBox => "LIGHT_GRAY_SHULKER_BOX",
            BlockType::CyanShulkerBox => "CYAN_SHULKER_BOX",
            BlockType::PurpleShulkerBox => "PURPLE_SHULKER_BOX",
            BlockType::BlueShulkerBox => "BLUE_SHULKER_BOX",
            BlockType::BrownShulkerBox => "BROWN_SHULKER_BOX",
            BlockType::GreenShulkerBox => "GREEN_SHULKER_BOX",
            BlockType::RedShulkerBox => "RED_SHULKER_BOX",
            BlockType::BlackShulkerBox => "BLACK_SHULKER_BOX",
        }
    }
}
