use crate::Result;
use crate::jni_utils::{JavaObject, get_env};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Block {
    // Basic blocks
    Air,
    Stone,
    Granite,
    PolishedGranite,
    Diorite,
    PolishedDiorite,
    Andesite,
    PolishedAndesite,
    GrassBlock,
    Dirt,
    CoarseDirt,
    Podzol,
    Cobblestone,

    // Wood types and variants
    OakPlanks,
    SprucePlanks,
    BirchPlanks,
    JunglePlanks,
    AcaciaPlanks,
    CherryPlanks,
    DarkOakPlanks,
    PaleOakWood,
    PaleOakPlanks,
    MangrovePlanks,
    BambooPlanks,
    BambooMosaic,

    // Saplings
    OakSapling,
    SpruceSapling,
    BirchSapling,
    JungleSapling,
    AcaciaSapling,
    CherrySapling,
    DarkOakSapling,
    PaleOakSapling,
    MangrovePropagule,

    // Base blocks
    Bedrock,
    Water,
    Lava,
    Sand,
    SuspiciousSand,
    RedSand,
    Gravel,
    SuspiciousGravel,

    // Ores
    GoldOre,
    DeepslateGoldOre,
    IronOre,
    DeepslateIronOre,
    CoalOre,
    DeepslateCoalOre,
    NetherGoldOre,
    LapisOre,
    DeepslateLapisOre,
    DiamondOre,
    DeepslateDiamondOre,
    RedstoneOre,
    DeepslateRedstoneOre,
    EmeraldOre,
    DeepslateEmeraldOre,
    CopperOre,
    DeepslateCopperOre,

    // Logs
    OakLog,
    SpruceLog,
    BirchLog,
    JungleLog,
    AcaciaLog,
    CherryLog,
    DarkOakLog,
    PaleOakLog,
    MangroveLog,
    MangroveRoots,
    MuddyMangroveRoots,
    BambooBlock,

    // Stripped logs
    StrippedSpruceLog,
    StrippedBirchLog,
    StrippedJungleLog,
    StrippedAcaciaLog,
    StrippedCherryLog,
    StrippedDarkOakLog,
    StrippedPaleOakLog,
    StrippedOakLog,
    StrippedMangroveLog,
    StrippedBambooBlock,

    // Wood blocks
    OakWood,
    SpruceWood,
    BirchWood,
    JungleWood,
    AcaciaWood,
    CherryWood,
    DarkOakWood,
    MangroveWood,

    // Stripped wood
    StrippedOakWood,
    StrippedSpruceWood,
    StrippedBirchWood,
    StrippedJungleWood,
    StrippedAcaciaWood,
    StrippedCherryWood,
    StrippedDarkOakWood,
    StrippedPaleOakWood,
    StrippedMangroveWood,

    // Leaves
    OakLeaves,
    SpruceLeaves,
    BirchLeaves,
    JungleLeaves,
    AcaciaLeaves,
    CherryLeaves,
    DarkOakLeaves,
    PaleOakLeaves,
    MangroveLeaves,
    AzaleaLeaves,
    FloweringAzaleaLeaves,

    // Utility blocks
    Sponge,
    WetSponge,
    Glass,
    LapisBlock,
    Dispenser,

    // Sandstone variants
    Sandstone,
    ChiseledSandstone,
    CutSandstone,
    SmoothSandstone,
    RedSandstone,
    ChiseledRedSandstone,
    CutRedSandstone,
    SmoothRedSandstone,

    // Functional blocks
    NoteBlock,
    PoweredRail,
    DetectorRail,
    StickyPiston,
    Cobweb,
    TallGrass,
    Fern,
    DeadBush,
    Seagrass,
    TallSeagrass,
    Piston,
    PistonHead,

    // Wool colors
    WhiteWool,
    OrangeWool,
    MagentaWool,
    LightBlueWool,
    YellowWool,
    LimeWool,
    PinkWool,
    GrayWool,
    LightGrayWool,
    CyanWool,
    PurpleWool,
    BlueWool,
    BrownWool,
    GreenWool,
    RedWool,
    BlackWool,

    // Flowers
    Dandelion,
    Poppy,
    BlueOrchid,
    Allium,
    AzureBluet,
    RedTulip,
    OrangeTulip,
    WhiteTulip,
    PinkTulip,
    OxeyeDaisy,
    Cornflower,
    LilyOfTheValley,
    WitherRose,

    // Mushrooms
    BrownMushroom,
    RedMushroom,
    MushroomStem,
    BrownMushroomBlock,
    RedMushroomBlock,

    // Metal blocks
    GoldBlock,
    IronBlock,
    DiamondBlock,
    EmeraldBlock,
    CopperBlock,

    // Building blocks
    Bricks,
    Tnt,
    Bookshelf,
    MossyCobblestone,
    Obsidian,
    Torch,
    WallTorch,
    Fire,
    SoulFire,

    // Colored Concrete
    WhiteConcrete,
    OrangeConcrete,
    MagentaConcrete,
    LightBlueConcrete,
    YellowConcrete,
    LimeConcrete,
    PinkConcrete,
    GrayConcrete,
    LightGrayConcrete,
    CyanConcrete,
    PurpleConcrete,
    BlueConcrete,
    BrownConcrete,
    GreenConcrete,
    RedConcrete,
    BlackConcrete,

    // Colored Concrete Powder
    WhiteConcretePowder,
    OrangeConcretePowder,
    MagentaConcretePowder,
    LightBlueConcretePowder,
    YellowConcretePowder,
    LimeConcretePowder,
    PinkConcretePowder,
    GrayConcretePowder,
    LightGrayConcretePowder,
    CyanConcretePowder,
    PurpleConcretePowder,
    BlueConcretePowder,
    BrownConcretePowder,
    GreenConcretePowder,
    RedConcretePowder,
    BlackConcretePowder,

    // Colored Terracotta
    WhiteTerracotta,
    OrangeTerracotta,
    MagentaTerracotta,
    LightBlueTerracotta,
    YellowTerracotta,
    LimeTerracotta,
    PinkTerracotta,
    GrayTerracotta,
    LightGrayTerracotta,
    CyanTerracotta,
    PurpleTerracotta,
    BlueTerracotta,
    BrownTerracotta,
    GreenTerracotta,
    RedTerracotta,
    BlackTerracotta,
    Terracotta,

    // Colored Stained Glass
    WhiteStainedGlass,
    OrangeStainedGlass,
    MagentaStainedGlass,
    LightBlueStainedGlass,
    YellowStainedGlass,
    LimeStainedGlass,
    PinkStainedGlass,
    GrayStainedGlass,
    LightGrayStainedGlass,
    CyanStainedGlass,
    PurpleStainedGlass,
    BlueStainedGlass,
    BrownStainedGlass,
    GreenStainedGlass,
    RedStainedGlass,
    BlackStainedGlass,

    // Stairs
    OakStairs,
    SpruceStairs,
    BirchStairs,
    JungleStairs,
    AcaciaStairs,
    DarkOakStairs,
    CrimsonStairs,
    WarpedStairs,
    StoneStairs,
    CobblestoneStairs,
    MossyCobblestoneStairs,
    StoneBrickStairs,
    MossyStoneBrickStairs,
    BrickStairs,
    SandstoneStairs,
    RedSandstoneStairs,
    NetherBrickStairs,
    QuartzStairs,
    PurpurStairs,

    // Slabs
    OakSlab,
    SpruceSlab,
    BirchSlab,
    JungleSlab,
    AcaciaSlab,
    DarkOakSlab,
    CrimsonSlab,
    WarpedSlab,
    StoneSlab,
    CobblestoneSlab,
    MossyCobblestoneSlab,
    StoneBrickSlab,
    MossyStoneBrickSlab,
    BrickSlab,
    SandstoneSlab,
    RedSandstoneSlab,
    NetherBrickSlab,
    QuartzSlab,
    PurpurSlab,

    // Walls
    CobblestoneWall,
    MossyCobblestoneWall,
    BrickWall,
    StoneBrickWall,
    MossyStoneBrickWall,
    SandstoneWall,
    RedSandstoneWall,
    NetherBrickWall,
    EndStoneBrickWall,
    PrismarineWall,

    // Doors
    OakDoor,
    SpruceDoor,
    BirchDoor,
    JungleDoor,
    AcaciaDoor,
    DarkOakDoor,
    CrimsonDoor,
    WarpedDoor,
    IronDoor,

    // Trapdoors
    OakTrapdoor,
    SpruceTrapdoor,
    BirchTrapdoor,
    JungleTrapdoor,
    AcaciaTrapdoor,
    DarkOakTrapdoor,
    CrimsonTrapdoor,
    WarpedTrapdoor,
    IronTrapdoor,

    // Pressure Plates
    OakPressurePlate,
    SprucePressurePlate,
    BirchPressurePlate,
    JunglePressurePlate,
    AcaciaPressurePlate,
    DarkOakPressurePlate,
    CrimsonPressurePlate,
    WarpedPressurePlate,
    StonePressurePlate,
    LightWeightedPressurePlate,
    HeavyWeightedPressurePlate,

    // Buttons
    OakButton,
    SpruceButton,
    BirchButton,
    JungleButton,
    AcaciaButton,
    DarkOakButton,
    CrimsonButton,
    WarpedButton,
    StoneButton,
    PolishedBlackstoneButton,

    // Redstone Components
    RedstoneWire,
    RedstoneTorch,
    RedstoneWallTorch,
    RepeatingRepeater,
    ComparatorRepeater,
    Lever,
    DaylightDetector,
    Hopper,
    Dropper,
    Observer,
    Target,

    // Decorative
    Ladder,
    Scaffolding,
    IronBars,
    Chain,
    GlassPane,
    Vine,
    Lily,
    EnderChest,
    Anvil,
    Grindstone,
    Lectern,
    Campfire,
    SoulCampfire,
    Lantern,
    SoulLantern,
    Bell,
    Barrel,
    Composter,
    Loom,
    Smoker,
    BlastFurnace,
    Cartography,
    FletchingTable,
    SmithingTable,
    Cauldron,
    Jukebox,
    Beacon,
    ConduitBlock,

    // Nether blocks
    NetherBricks,
    ChiseledNetherBricks,
    CrackedNetherBricks,
    NetherWart,
    NetherWartBlock,
    Netherrack,
    SoulSand,
    SoulSoil,
    Basalt,
    PolishedBasalt,
    Blackstone,
    PolishedBlackstone,
    ChiseledPolishedBlackstone,
    PolishedBlackstoneBricks,
    CrackedPolishedBlackstoneBricks,
    GildedBlackstone,
    QuartzBlock,
    ChiseledQuartzBlock,
    QuartzBricks,
    QuartzPillar,
    SmoothQuartz,
    Glowstone,
    CryingObsidian,
    RespawnAnchor,
    AncientDebris,
    NetheriteBlock,

    // End blocks
    EndStone,
    EndStoneBricks,
    DragonEgg,
    Chorus,
    ChorusFlower,
    ChorusPlant,
    PurpurBlock,
    PurpurPillar,
    EndRod,

    // Ocean blocks
    Prismarine,
    PrismarineBricks,
    DarkPrismarine,
    SeaLantern,
    Kelp,
    KelpPlant,
    SeaPickle,
    TurtleEgg,
    DriedKelpBlock,

    // Snow and ice
    Snow,
    SnowBlock,
    Ice,
    PackedIce,
    BlueIce,
    FrostedIce,

    // Miscellaneous
    SlimeBlock,
    HoneyBlock,
    HoneycombBlock,
    Hay,
    BoneBlock,
    DriedKelp,
    Bamboo,
    BambooSapling,
    PottedBamboo,
    FlowerPot,
    Cactus,
    Cake,
    Cookie,
    MelonBlock,
    PumpkinBlock,
    CarvedPumpkin,
    JackOLantern,
    Beetroots,
    Carrots,
    Potatoes,
    Wheat,
    FarmLand,
    CommandBlock,
    ChainCommandBlock,
    RepeatingCommandBlock,
    StructureBlock,
    JigsawBlock,
    Barrier,
    Light,
    VoidAir,
    CaveAir,
    BubbleColumn,

    // Shulker boxes
    ShulkerBox,
    WhiteShulkerBox,
    OrangeShulkerBox,
    MagentaShulkerBox,
    LightBlueShulkerBox,
    YellowShulkerBox,
    LimeShulkerBox,
    PinkShulkerBox,
    GrayShulkerBox,
    LightGrayShulkerBox,
    CyanShulkerBox,
    PurpleShulkerBox,
    BlueShulkerBox,
    BrownShulkerBox,
    GreenShulkerBox,
    RedShulkerBox,
    BlackShulkerBox,
}

impl Block {
    pub(crate) fn to_java_block(&self) -> Result<JavaObject> {
        let mut env = get_env()?;

        // Get the Block class
        let block_class = env.find_class("net/minestom/server/instance/block/Block")?;

        // Get the static block field
        let field_name = self.to_field_name();
        let block = env
            .get_static_field(
                block_class,
                field_name,
                "Lnet/minestom/server/instance/block/Block;",
            )?
            .l()?;

        Ok(JavaObject::from_env(&mut env, block)?)
    }

    fn to_field_name(&self) -> &'static str {
        match self {
            // Basic blocks
            Block::Air => "AIR",
            Block::Stone => "STONE",
            Block::Granite => "GRANITE",
            Block::PolishedGranite => "POLISHED_GRANITE",
            Block::Diorite => "DIORITE",
            Block::PolishedDiorite => "POLISHED_DIORITE",
            Block::Andesite => "ANDESITE",
            Block::PolishedAndesite => "POLISHED_ANDESITE",
            Block::GrassBlock => "GRASS_BLOCK",
            Block::Dirt => "DIRT",
            Block::CoarseDirt => "COARSE_DIRT",
            Block::Podzol => "PODZOL",
            Block::Cobblestone => "COBBLESTONE",

            // Ores
            Block::GoldOre => "GOLD_ORE",
            Block::DeepslateGoldOre => "DEEPSLATE_GOLD_ORE",
            Block::IronOre => "IRON_ORE",
            Block::DeepslateIronOre => "DEEPSLATE_IRON_ORE",
            Block::CoalOre => "COAL_ORE",
            Block::DeepslateCoalOre => "DEEPSLATE_COAL_ORE",
            Block::NetherGoldOre => "NETHER_GOLD_ORE",
            Block::DiamondOre => "DIAMOND_ORE",
            Block::DeepslateDiamondOre => "DEEPSLATE_DIAMOND_ORE",
            Block::RedstoneOre => "REDSTONE_ORE",
            Block::DeepslateRedstoneOre => "DEEPSLATE_REDSTONE_ORE",
            Block::EmeraldOre => "EMERALD_ORE",
            Block::DeepslateEmeraldOre => "DEEPSLATE_EMERALD_ORE",
            Block::CopperOre => "COPPER_ORE",
            Block::DeepslateCopperOre => "DEEPSLATE_COPPER_ORE",
            Block::LapisOre => "LAPIS_ORE",
            Block::DeepslateLapisOre => "DEEPSLATE_LAPIS_ORE",

            // Wood types and variants
            Block::OakPlanks => "OAK_PLANKS",
            Block::SprucePlanks => "SPRUCE_PLANKS",
            Block::BirchPlanks => "BIRCH_PLANKS",
            Block::JunglePlanks => "JUNGLE_PLANKS",
            Block::AcaciaPlanks => "ACACIA_PLANKS",
            Block::CherryPlanks => "CHERRY_PLANKS",
            Block::DarkOakPlanks => "DARK_OAK_PLANKS",
            Block::PaleOakWood => "PALE_OAK_WOOD",
            Block::PaleOakPlanks => "PALE_OAK_PLANKS",
            Block::MangrovePlanks => "MANGROVE_PLANKS",
            Block::BambooPlanks => "BAMBOO_PLANKS",
            Block::BambooMosaic => "BAMBOO_MOSAIC",

            // Saplings
            Block::OakSapling => "OAK_SAPLING",
            Block::SpruceSapling => "SPRUCE_SAPLING",
            Block::BirchSapling => "BIRCH_SAPLING",
            Block::JungleSapling => "JUNGLE_SAPLING",
            Block::AcaciaSapling => "ACACIA_SAPLING",
            Block::CherrySapling => "CHERRY_SAPLING",
            Block::DarkOakSapling => "DARK_OAK_SAPLING",
            Block::PaleOakSapling => "PALE_OAK_SAPLING",
            Block::MangrovePropagule => "MANGROVE_PROPAGULE",

            // Base blocks
            Block::Bedrock => "BEDROCK",
            Block::Water => "WATER",
            Block::Lava => "LAVA",
            Block::Sand => "SAND",
            Block::SuspiciousSand => "SUSPICIOUS_SAND",
            Block::RedSand => "RED_SAND",
            Block::Gravel => "GRAVEL",
            Block::SuspiciousGravel => "SUSPICIOUS_GRAVEL",

            // Logs
            Block::OakLog => "OAK_LOG",
            Block::SpruceLog => "SPRUCE_LOG",
            Block::BirchLog => "BIRCH_LOG",
            Block::JungleLog => "JUNGLE_LOG",
            Block::AcaciaLog => "ACACIA_LOG",
            Block::CherryLog => "CHERRY_LOG",
            Block::DarkOakLog => "DARK_OAK_LOG",
            Block::PaleOakLog => "PALE_OAK_LOG",
            Block::MangroveLog => "MANGROVE_LOG",
            Block::MangroveRoots => "MANGROVE_ROOTS",
            Block::MuddyMangroveRoots => "MUDDY_MANGROVE_ROOTS",
            Block::BambooBlock => "BAMBOO_BLOCK",

            // Stripped logs
            Block::StrippedSpruceLog => "STRIPPED_SPRUCE_LOG",
            Block::StrippedBirchLog => "STRIPPED_BIRCH_LOG",
            Block::StrippedJungleLog => "STRIPPED_JUNGLE_LOG",
            Block::StrippedAcaciaLog => "STRIPPED_ACACIA_LOG",
            Block::StrippedCherryLog => "STRIPPED_CHERRY_LOG",
            Block::StrippedDarkOakLog => "STRIPPED_DARK_OAK_LOG",
            Block::StrippedPaleOakLog => "STRIPPED_PALE_OAK_LOG",
            Block::StrippedOakLog => "STRIPPED_OAK_LOG",
            Block::StrippedMangroveLog => "STRIPPED_MANGROVE_LOG",
            Block::StrippedBambooBlock => "STRIPPED_BAMBOO_BLOCK",

            // Wood blocks
            Block::OakWood => "OAK_WOOD",
            Block::SpruceWood => "SPRUCE_WOOD",
            Block::BirchWood => "BIRCH_WOOD",
            Block::JungleWood => "JUNGLE_WOOD",
            Block::AcaciaWood => "ACACIA_WOOD",
            Block::CherryWood => "CHERRY_WOOD",
            Block::DarkOakWood => "DARK_OAK_WOOD",
            Block::MangroveWood => "MANGROVE_WOOD",

            // Stripped wood
            Block::StrippedOakWood => "STRIPPED_OAK_WOOD",
            Block::StrippedSpruceWood => "STRIPPED_SPRUCE_WOOD",
            Block::StrippedBirchWood => "STRIPPED_BIRCH_WOOD",
            Block::StrippedJungleWood => "STRIPPED_JUNGLE_WOOD",
            Block::StrippedAcaciaWood => "STRIPPED_ACACIA_WOOD",
            Block::StrippedCherryWood => "STRIPPED_CHERRY_WOOD",
            Block::StrippedDarkOakWood => "STRIPPED_DARK_OAK_WOOD",
            Block::StrippedPaleOakWood => "STRIPPED_PALE_OAK_WOOD",
            Block::StrippedMangroveWood => "STRIPPED_MANGROVE_WOOD",

            // Leaves
            Block::OakLeaves => "OAK_LEAVES",
            Block::SpruceLeaves => "SPRUCE_LEAVES",
            Block::BirchLeaves => "BIRCH_LEAVES",
            Block::JungleLeaves => "JUNGLE_LEAVES",
            Block::AcaciaLeaves => "ACACIA_LEAVES",
            Block::CherryLeaves => "CHERRY_LEAVES",
            Block::DarkOakLeaves => "DARK_OAK_LEAVES",
            Block::PaleOakLeaves => "PALE_OAK_LEAVES",
            Block::MangroveLeaves => "MANGROVE_LEAVES",
            Block::AzaleaLeaves => "AZALEA_LEAVES",
            Block::FloweringAzaleaLeaves => "FLOWERING_AZALEA_LEAVES",

            // Utility blocks
            Block::Sponge => "SPONGE",
            Block::WetSponge => "WET_SPONGE",
            Block::Glass => "GLASS",
            Block::LapisBlock => "LAPIS_BLOCK",
            Block::Dispenser => "DISPENSER",

            // Sandstone variants
            Block::Sandstone => "SANDSTONE",
            Block::ChiseledSandstone => "CHISELED_SANDSTONE",
            Block::CutSandstone => "CUT_SANDSTONE",
            Block::SmoothSandstone => "SMOOTH_SANDSTONE",
            Block::RedSandstone => "RED_SANDSTONE",
            Block::ChiseledRedSandstone => "CHISELED_RED_SANDSTONE",
            Block::CutRedSandstone => "CUT_RED_SANDSTONE",
            Block::SmoothRedSandstone => "SMOOTH_RED_SANDSTONE",

            // Functional blocks
            Block::NoteBlock => "NOTE_BLOCK",
            Block::PoweredRail => "POWERED_RAIL",
            Block::DetectorRail => "DETECTOR_RAIL",
            Block::StickyPiston => "STICKY_PISTON",
            Block::Cobweb => "COBWEB",
            Block::TallGrass => "TALL_GRASS",
            Block::Fern => "FERN",
            Block::DeadBush => "DEAD_BUSH",
            Block::Seagrass => "SEAGRASS",
            Block::TallSeagrass => "TALL_SEAGRASS",
            Block::Piston => "PISTON",
            Block::PistonHead => "PISTON_HEAD",

            // Wool colors
            Block::WhiteWool => "WHITE_WOOL",
            Block::OrangeWool => "ORANGE_WOOL",
            Block::MagentaWool => "MAGENTA_WOOL",
            Block::LightBlueWool => "LIGHT_BLUE_WOOL",
            Block::YellowWool => "YELLOW_WOOL",
            Block::LimeWool => "LIME_WOOL",
            Block::PinkWool => "PINK_WOOL",
            Block::GrayWool => "GRAY_WOOL",
            Block::LightGrayWool => "LIGHT_GRAY_WOOL",
            Block::CyanWool => "CYAN_WOOL",
            Block::PurpleWool => "PURPLE_WOOL",
            Block::BlueWool => "BLUE_WOOL",
            Block::BrownWool => "BROWN_WOOL",
            Block::GreenWool => "GREEN_WOOL",
            Block::RedWool => "RED_WOOL",
            Block::BlackWool => "BLACK_WOOL",

            // Flowers
            Block::Dandelion => "DANDELION",
            Block::Poppy => "POPPY",
            Block::BlueOrchid => "BLUE_ORCHID",
            Block::Allium => "ALLIUM",
            Block::AzureBluet => "AZURE_BLUET",
            Block::RedTulip => "RED_TULIP",
            Block::OrangeTulip => "ORANGE_TULIP",
            Block::WhiteTulip => "WHITE_TULIP",
            Block::PinkTulip => "PINK_TULIP",
            Block::OxeyeDaisy => "OXEYE_DAISY",
            Block::Cornflower => "CORNFLOWER",
            Block::LilyOfTheValley => "LILY_OF_THE_VALLEY",
            Block::WitherRose => "WITHER_ROSE",

            // Mushrooms
            Block::BrownMushroom => "BROWN_MUSHROOM",
            Block::RedMushroom => "RED_MUSHROOM",
            Block::MushroomStem => "MUSHROOM_STEM",
            Block::BrownMushroomBlock => "BROWN_MUSHROOM_BLOCK",
            Block::RedMushroomBlock => "RED_MUSHROOM_BLOCK",

            // Metal blocks
            Block::GoldBlock => "GOLD_BLOCK",
            Block::IronBlock => "IRON_BLOCK",
            Block::DiamondBlock => "DIAMOND_BLOCK",
            Block::EmeraldBlock => "EMERALD_BLOCK",
            Block::CopperBlock => "COPPER_BLOCK",

            // Building blocks
            Block::Bricks => "BRICKS",
            Block::Tnt => "TNT",
            Block::Bookshelf => "BOOKSHELF",
            Block::MossyCobblestone => "MOSSY_COBBLESTONE",
            Block::Obsidian => "OBSIDIAN",
            Block::Torch => "TORCH",
            Block::WallTorch => "WALL_TORCH",
            Block::Fire => "FIRE",
            Block::SoulFire => "SOUL_FIRE",

            // Colored Concrete
            Block::WhiteConcrete => "WHITE_CONCRETE",
            Block::OrangeConcrete => "ORANGE_CONCRETE",
            Block::MagentaConcrete => "MAGENTA_CONCRETE",
            Block::LightBlueConcrete => "LIGHT_BLUE_CONCRETE",
            Block::YellowConcrete => "YELLOW_CONCRETE",
            Block::LimeConcrete => "LIME_CONCRETE",
            Block::PinkConcrete => "PINK_CONCRETE",
            Block::GrayConcrete => "GRAY_CONCRETE",
            Block::LightGrayConcrete => "LIGHT_GRAY_CONCRETE",
            Block::CyanConcrete => "CYAN_CONCRETE",
            Block::PurpleConcrete => "PURPLE_CONCRETE",
            Block::BlueConcrete => "BLUE_CONCRETE",
            Block::BrownConcrete => "BROWN_CONCRETE",
            Block::GreenConcrete => "GREEN_CONCRETE",
            Block::RedConcrete => "RED_CONCRETE",
            Block::BlackConcrete => "BLACK_CONCRETE",

            // Colored Concrete Powder
            Block::WhiteConcretePowder => "WHITE_CONCRETE_POWDER",
            Block::OrangeConcretePowder => "ORANGE_CONCRETE_POWDER",
            Block::MagentaConcretePowder => "MAGENTA_CONCRETE_POWDER",
            Block::LightBlueConcretePowder => "LIGHT_BLUE_CONCRETE_POWDER",
            Block::YellowConcretePowder => "YELLOW_CONCRETE_POWDER",
            Block::LimeConcretePowder => "LIME_CONCRETE_POWDER",
            Block::PinkConcretePowder => "PINK_CONCRETE_POWDER",
            Block::GrayConcretePowder => "GRAY_CONCRETE_POWDER",
            Block::LightGrayConcretePowder => "LIGHT_GRAY_CONCRETE_POWDER",
            Block::CyanConcretePowder => "CYAN_CONCRETE_POWDER",
            Block::PurpleConcretePowder => "PURPLE_CONCRETE_POWDER",
            Block::BlueConcretePowder => "BLUE_CONCRETE_POWDER",
            Block::BrownConcretePowder => "BROWN_CONCRETE_POWDER",
            Block::GreenConcretePowder => "GREEN_CONCRETE_POWDER",
            Block::RedConcretePowder => "RED_CONCRETE_POWDER",
            Block::BlackConcretePowder => "BLACK_CONCRETE_POWDER",

            // Colored Terracotta
            Block::WhiteTerracotta => "WHITE_TERRACOTTA",
            Block::OrangeTerracotta => "ORANGE_TERRACOTTA",
            Block::MagentaTerracotta => "MAGENTA_TERRACOTTA",
            Block::LightBlueTerracotta => "LIGHT_BLUE_TERRACOTTA",
            Block::YellowTerracotta => "YELLOW_TERRACOTTA",
            Block::LimeTerracotta => "LIME_TERRACOTTA",
            Block::PinkTerracotta => "PINK_TERRACOTTA",
            Block::GrayTerracotta => "GRAY_TERRACOTTA",
            Block::LightGrayTerracotta => "LIGHT_GRAY_TERRACOTTA",
            Block::CyanTerracotta => "CYAN_TERRACOTTA",
            Block::PurpleTerracotta => "PURPLE_TERRACOTTA",
            Block::BlueTerracotta => "BLUE_TERRACOTTA",
            Block::BrownTerracotta => "BROWN_TERRACOTTA",
            Block::GreenTerracotta => "GREEN_TERRACOTTA",
            Block::RedTerracotta => "RED_TERRACOTTA",
            Block::BlackTerracotta => "BLACK_TERRACOTTA",
            Block::Terracotta => "TERRACOTTA",

            // Colored Stained Glass
            Block::WhiteStainedGlass => "WHITE_STAINED_GLASS",
            Block::OrangeStainedGlass => "ORANGE_STAINED_GLASS",
            Block::MagentaStainedGlass => "MAGENTA_STAINED_GLASS",
            Block::LightBlueStainedGlass => "LIGHT_BLUE_STAINED_GLASS",
            Block::YellowStainedGlass => "YELLOW_STAINED_GLASS",
            Block::LimeStainedGlass => "LIME_STAINED_GLASS",
            Block::PinkStainedGlass => "PINK_STAINED_GLASS",
            Block::GrayStainedGlass => "GRAY_STAINED_GLASS",
            Block::LightGrayStainedGlass => "LIGHT_GRAY_STAINED_GLASS",
            Block::CyanStainedGlass => "CYAN_STAINED_GLASS",
            Block::PurpleStainedGlass => "PURPLE_STAINED_GLASS",
            Block::BlueStainedGlass => "BLUE_STAINED_GLASS",
            Block::BrownStainedGlass => "BROWN_STAINED_GLASS",
            Block::GreenStainedGlass => "GREEN_STAINED_GLASS",
            Block::RedStainedGlass => "RED_STAINED_GLASS",
            Block::BlackStainedGlass => "BLACK_STAINED_GLASS",

            // Stairs
            Block::OakStairs => "OAK_STAIRS",
            Block::SpruceStairs => "SPRUCE_STAIRS",
            Block::BirchStairs => "BIRCH_STAIRS",
            Block::JungleStairs => "JUNGLE_STAIRS",
            Block::AcaciaStairs => "ACACIA_STAIRS",
            Block::DarkOakStairs => "DARK_OAK_STAIRS",
            Block::CrimsonStairs => "CRIMSON_STAIRS",
            Block::WarpedStairs => "WARPED_STAIRS",
            Block::StoneStairs => "STONE_STAIRS",
            Block::CobblestoneStairs => "COBBLESTONE_STAIRS",
            Block::MossyCobblestoneStairs => "MOSSY_COBBLESTONE_STAIRS",
            Block::StoneBrickStairs => "STONE_BRICK_STAIRS",
            Block::MossyStoneBrickStairs => "MOSSY_STONE_BRICK_STAIRS",
            Block::BrickStairs => "BRICK_STAIRS",
            Block::SandstoneStairs => "SANDSTONE_STAIRS",
            Block::RedSandstoneStairs => "RED_SANDSTONE_STAIRS",
            Block::NetherBrickStairs => "NETHER_BRICK_STAIRS",
            Block::QuartzStairs => "QUARTZ_STAIRS",
            Block::PurpurStairs => "PURPUR_STAIRS",
            Block::OakSlab => "OAK_SLAB",
            Block::SpruceSlab => "SPRUCE_SLAB",
            Block::BirchSlab => "BIRCH_SLAB",
            Block::JungleSlab => "JUNGLE_SLAB",
            Block::AcaciaSlab => "ACACIA_SLAB",
            Block::DarkOakSlab => "DARK_OAK_SLAB",
            Block::CrimsonSlab => "CRIMSON_SLAB",
            Block::WarpedSlab => "WARPED_SLAB",
            Block::StoneSlab => "STONE_SLAB",
            Block::CobblestoneSlab => "COBBLESTONE_SLAB",
            Block::MossyCobblestoneSlab => "MOSSY_COBBLESTONE_SLAB",
            Block::StoneBrickSlab => "STONE_BRICK_SLAB",
            Block::MossyStoneBrickSlab => "MOSSY_STONE_BRICK_SLAB",
            Block::BrickSlab => "BRICK_SLAB",
            Block::SandstoneSlab => "SANDSTONE_SLAB",
            Block::RedSandstoneSlab => "RED_SANDSTONE_SLAB",
            Block::NetherBrickSlab => "NETHER_BRICK_SLAB",
            Block::QuartzSlab => "QUARTZ_SLAB",
            Block::PurpurSlab => "PURPUR_SLAB",
            Block::CobblestoneWall => "COBBLESTONE_WALL",
            Block::MossyCobblestoneWall => "MOSSY_COBBLESTONE_WALL",
            Block::BrickWall => "BRICK_WALL",
            Block::StoneBrickWall => "STONE_BRICK_WALL",
            Block::MossyStoneBrickWall => "MOSSY_STONE_BRICK_WALL",
            Block::SandstoneWall => "SANDSTONE_WALL",
            Block::RedSandstoneWall => "RED_SANDSTONE_WALL",
            Block::NetherBrickWall => "NETHER_BRICK_WALL",
            Block::EndStoneBrickWall => "END_STONE_BRICK_WALL",
            Block::PrismarineWall => "PRISMARINE_WALL",
            Block::OakDoor => "OAK_DOOR",
            Block::SpruceDoor => "SPRUCE_DOOR",
            Block::BirchDoor => "BIRCH_DOOR",
            Block::JungleDoor => "JUNGLE_DOOR",
            Block::AcaciaDoor => "ACACIA_DOOR",
            Block::DarkOakDoor => "DARK_OAK_DOOR",
            Block::CrimsonDoor => "CRIMSON_DOOR",
            Block::WarpedDoor => "WARPED_DOOR",
            Block::IronDoor => "IRON_DOOR",
            Block::OakTrapdoor => "OAK_TRAPDOOR",
            Block::SpruceTrapdoor => "SPRUCE_TRAPDOOR",
            Block::BirchTrapdoor => "BIRCH_TRAPDOOR",
            Block::JungleTrapdoor => "JUNGLE_TRAPDOOR",
            Block::AcaciaTrapdoor => "ACACIA_TRAPDOOR",
            Block::DarkOakTrapdoor => "DARK_OAK_TRAPDOOR",
            Block::CrimsonTrapdoor => "CRIMSON_TRAPDOOR",
            Block::WarpedTrapdoor => "WARPED_TRAPDOOR",
            Block::IronTrapdoor => "IRON_TRAPDOOR",
            Block::OakPressurePlate => "OAK_PRESSURE_PLATE",
            Block::SprucePressurePlate => "SPRUCE_PRESSURE_PLATE",
            Block::BirchPressurePlate => "BIRCH_PRESSURE_PLATE",
            Block::JunglePressurePlate => "JUNGLE_PRESSURE_PLATE",
            Block::AcaciaPressurePlate => "ACACIA_PRESSURE_PLATE",
            Block::DarkOakPressurePlate => "DARK_OAK_PRESSURE_PLATE",
            Block::CrimsonPressurePlate => "CRIMSON_PRESSURE_PLATE",
            Block::WarpedPressurePlate => "WARPED_PRESSURE_PLATE",
            Block::StonePressurePlate => "STONE_PRESSURE_PLATE",
            Block::LightWeightedPressurePlate => "LIGHT_WEIGHTED_PRESSURE_PLATE",
            Block::HeavyWeightedPressurePlate => "HEAVY_WEIGHTED_PRESSURE_PLATE",
            Block::OakButton => "OAK_BUTTON",
            Block::SpruceButton => "SPRUCE_BUTTON",
            Block::BirchButton => "BIRCH_BUTTON",
            Block::JungleButton => "JUNGLE_BUTTON",
            Block::AcaciaButton => "ACACIA_BUTTON",
            Block::DarkOakButton => "DARK_OAK_BUTTON",
            Block::CrimsonButton => "CRIMSON_BUTTON",
            Block::WarpedButton => "WARPED_BUTTON",
            Block::StoneButton => "STONE_BUTTON",
            Block::PolishedBlackstoneButton => "POLISHED_BLACKSTONE_BUTTON",
            Block::RedstoneWire => "REDSTONE_WIRE",
            Block::RedstoneTorch => "REDSTONE_TORCH",
            Block::RedstoneWallTorch => "REDSTONE_WALL_TORCH",
            Block::RepeatingRepeater => "REPEATING_REPEATER",
            Block::ComparatorRepeater => "COMPARATOR_REPEATER",
            Block::Lever => "LEVER",
            Block::DaylightDetector => "DAYLIGHT_DETECTOR",
            Block::Hopper => "HOPPER",
            Block::Dropper => "DROPPER",
            Block::Observer => "OBSERVER",
            Block::Target => "TARGET",
            Block::Ladder => "LADDER",
            Block::Scaffolding => "SCAFFOLDING",
            Block::IronBars => "IRON_BARS",
            Block::Chain => "CHAIN",
            Block::GlassPane => "GLASS_PANE",
            Block::Vine => "VINE",
            Block::Lily => "LILY",
            Block::EnderChest => "ENDER_CHEST",
            Block::Anvil => "ANVIL",
            Block::Grindstone => "GRINDSTONE",
            Block::Lectern => "LECTERN",
            Block::Campfire => "CAMPFIRE",
            Block::SoulCampfire => "SOUL_CAMPFIRE",
            Block::Lantern => "LANTERN",
            Block::SoulLantern => "SOUL_LANTERN",
            Block::Bell => "BELL",
            Block::Barrel => "BARREL",
            Block::Composter => "COMPOSTER",
            Block::Loom => "LOOM",
            Block::Smoker => "SMOKER",
            Block::BlastFurnace => "BLAST_FURNACE",
            Block::Cartography => "CARTOGRAPHY_TABLE",
            Block::FletchingTable => "FLETCHING_TABLE",
            Block::SmithingTable => "SMITHING_TABLE",
            Block::Cauldron => "CAULDRON",
            Block::Jukebox => "JUKEBOX",
            Block::Beacon => "BEACON",
            Block::ConduitBlock => "CONDUIT",

            // Nether blocks
            Block::NetherBricks => "NETHER_BRICKS",
            Block::ChiseledNetherBricks => "CHISELED_NETHER_BRICKS",
            Block::CrackedNetherBricks => "CRACKED_NETHER_BRICKS",
            Block::NetherWart => "NETHER_WART",
            Block::NetherWartBlock => "NETHER_WART_BLOCK",
            Block::Netherrack => "NETHERRACK",
            Block::SoulSand => "SOUL_SAND",
            Block::SoulSoil => "SOUL_SOIL",
            Block::Basalt => "BASALT",
            Block::PolishedBasalt => "POLISHED_BASALT",
            Block::Blackstone => "BLACKSTONE",
            Block::PolishedBlackstone => "POLISHED_BLACKSTONE",
            Block::ChiseledPolishedBlackstone => "CHISELED_POLISHED_BLACKSTONE",
            Block::PolishedBlackstoneBricks => "POLISHED_BLACKSTONE_BRICKS",
            Block::CrackedPolishedBlackstoneBricks => "CRACKED_POLISHED_BLACKSTONE_BRICKS",
            Block::GildedBlackstone => "GILDED_BLACKSTONE",
            Block::QuartzBlock => "QUARTZ_BLOCK",
            Block::ChiseledQuartzBlock => "CHISELED_QUARTZ_BLOCK",
            Block::QuartzBricks => "QUARTZ_BRICKS",
            Block::QuartzPillar => "QUARTZ_PILLAR",
            Block::SmoothQuartz => "SMOOTH_QUARTZ",
            Block::Glowstone => "GLOWSTONE",
            Block::CryingObsidian => "CRYING_OBSIDIAN",
            Block::RespawnAnchor => "RESPAWN_ANCHOR",
            Block::AncientDebris => "ANCIENT_DEBRIS",
            Block::NetheriteBlock => "NETHERITE_BLOCK",

            // End blocks
            Block::EndStone => "END_STONE",
            Block::EndStoneBricks => "END_STONE_BRICKS",
            Block::DragonEgg => "DRAGON_EGG",
            Block::Chorus => "CHORUS",
            Block::ChorusFlower => "CHORUS_FLOWER",
            Block::ChorusPlant => "CHORUS_PLANT",
            Block::PurpurBlock => "PURPUR_BLOCK",
            Block::PurpurPillar => "PURPUR_PILLAR",
            Block::EndRod => "END_ROD",

            // Ocean blocks
            Block::Prismarine => "PRISMARINE",
            Block::PrismarineBricks => "PRISMARINE_BRICKS",
            Block::DarkPrismarine => "DARK_PRISMARINE",
            Block::SeaLantern => "SEA_LANTERN",
            Block::Kelp => "KELP",
            Block::KelpPlant => "KELP_PLANT",
            Block::SeaPickle => "SEA_PICKLE",
            Block::TurtleEgg => "TURTLE_EGG",
            Block::DriedKelpBlock => "DRIED_KELP_BLOCK",

            // Snow and ice
            Block::Snow => "SNOW",
            Block::SnowBlock => "SNOW_BLOCK",
            Block::Ice => "ICE",
            Block::PackedIce => "PACKED_ICE",
            Block::BlueIce => "BLUE_ICE",
            Block::FrostedIce => "FROSTED_ICE",

            // Miscellaneous
            Block::SlimeBlock => "SLIME_BLOCK",
            Block::HoneyBlock => "HONEY_BLOCK",
            Block::HoneycombBlock => "HONEYCOMB_BLOCK",
            Block::Hay => "HAY_BLOCK",
            Block::BoneBlock => "BONE_BLOCK",
            Block::DriedKelp => "DRIED_KELP",
            Block::Bamboo => "BAMBOO",
            Block::BambooSapling => "BAMBOO_SAPLING",
            Block::PottedBamboo => "POTTED_BAMBOO",
            Block::FlowerPot => "FLOWER_POT",
            Block::Cactus => "CACTUS",
            Block::Cake => "CAKE",
            Block::Cookie => "COOKIE",
            Block::MelonBlock => "MELON",
            Block::PumpkinBlock => "PUMPKIN",
            Block::CarvedPumpkin => "CARVED_PUMPKIN",
            Block::JackOLantern => "JACK_O_LANTERN",
            Block::Beetroots => "BEETROOTS",
            Block::Carrots => "CARROTS",
            Block::Potatoes => "POTATOES",
            Block::Wheat => "WHEAT",
            Block::FarmLand => "FARMLAND",
            Block::CommandBlock => "COMMAND_BLOCK",
            Block::ChainCommandBlock => "CHAIN_COMMAND_BLOCK",
            Block::RepeatingCommandBlock => "REPEATING_COMMAND_BLOCK",
            Block::StructureBlock => "STRUCTURE_BLOCK",
            Block::JigsawBlock => "JIGSAW",
            Block::Barrier => "BARRIER",
            Block::Light => "LIGHT",
            Block::VoidAir => "VOID_AIR",
            Block::CaveAir => "CAVE_AIR",
            Block::BubbleColumn => "BUBBLE_COLUMN",

            // Shulker boxes
            Block::ShulkerBox => "SHULKER_BOX",
            Block::WhiteShulkerBox => "WHITE_SHULKER_BOX",
            Block::OrangeShulkerBox => "ORANGE_SHULKER_BOX",
            Block::MagentaShulkerBox => "MAGENTA_SHULKER_BOX",
            Block::LightBlueShulkerBox => "LIGHT_BLUE_SHULKER_BOX",
            Block::YellowShulkerBox => "YELLOW_SHULKER_BOX",
            Block::LimeShulkerBox => "LIME_SHULKER_BOX",
            Block::PinkShulkerBox => "PINK_SHULKER_BOX",
            Block::GrayShulkerBox => "GRAY_SHULKER_BOX",
            Block::LightGrayShulkerBox => "LIGHT_GRAY_SHULKER_BOX",
            Block::CyanShulkerBox => "CYAN_SHULKER_BOX",
            Block::PurpleShulkerBox => "PURPLE_SHULKER_BOX",
            Block::BlueShulkerBox => "BLUE_SHULKER_BOX",
            Block::BrownShulkerBox => "BROWN_SHULKER_BOX",
            Block::GreenShulkerBox => "GREEN_SHULKER_BOX",
            Block::RedShulkerBox => "RED_SHULKER_BOX",
            Block::BlackShulkerBox => "BLACK_SHULKER_BOX",
        }
    }
}
