[package]
name = "thecrown-components"
version = "0.1.0"
edition = "2024"

[dependencies]
minestom ={ workspace = true }
once_cell ={ workspace = true }
parking_lot ={ workspace = true }
uuid ={ workspace = true }